config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticate :user do
    root to: 'home#index'

    resources :lists, only: [:new, :create, :show] do
      member do
        get 'favorite'
        get 'unfavorite'
        get 'mark_public_list'
        get 'unmark_public_list'
      end

      resources :tasks, only: [:create, :update, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_list.rb
class FavoriteList < ActiveRecord::Base
  belongs_to :user
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks

  validates_presence_of :name, :user_id

  def created_by?(user)
    user_id == user.id
  end

  def add_mark_public(list)
    mark_public(list, true)
  end

  def remove_mark_public(list)
    mark_public(list, false)
  end

  def mark_public(list, value=true)
    list.update_columns(public: value)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates_presence_of :name, :list_id

  after_save :verify_done

  def verify_done
    slist = self.list
    if !slist.nil?
      number_tasks = slist.tasks.count
      tasks = slist.tasks
      tasks_done = []
      tasks.each do |task|
        if task.done
          tasks_done.push(true)
        end
      end
      if tasks_done.count == number_tasks
        slist.update_columns(done: true)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
  has_many :favorite_lists, -> { joins(:list).select('lists.id AS list_id, lists.name AS list_name') }
  
  validates_presence_of :name, :encrypted_password, :email

  def get_showable_lists
    lists.where("public = ? or user_id = ?", true, self.id)
  end

  def favorited?(list)
    favorite_lists.map(&:list_id).include?(list.id)
  end

  def add_favorite_list(list)
    unless favorited? list
      favorite_lists << FavoriteList.new(list_id: list.id)
    end
  end

  def remove_favorite_list(list)
    FavoriteList.find_by(user_id: id, list_id: list.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @lists = current_user.get_showable_lists
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def show
    @list = List.find(id)

    unless @list.created_by?(current_user) or @list.public?
      redirect_to root_path
    end
  end

  def create
    @list = current_user.lists.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def unfavorite
    current_user.remove_favorite_list(List.find(params[:id]))

    render nothing: true
  end

  def favorite
    current_user.add_favorite_list(List.find(params[:id]))

    render nothing: true
  end

  def unmark_public_list
    list = List.find(params[:id])
    List.new.remove_mark_public(list)

    render nothing: true
  end

  def mark_public_list
    list = List.find(params[:id])
    List.new.add_mark_public(list)

    render nothing: true
  end

  def copy_list
    @list = List.new.copy_list(List.find(id), current_user)
    redirect_to @list
  end

  private

  def list_params
    params.require(:list).permit(:name, :public_list)
  end

  def id
    params[:id]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    task = Task.new(task_params)

    if task.save
      render json: { name: task.name, url: list_task_path(task.list_id, task.id) }
    else
      render json: { errors: task.errors.full_messages }, status: 422
    end
  end

  def update
    task = Task.find(task_id)

    task.update_attributes(update_task_params)

    render json: { name: task.name }
  end

  def show
    @task = Task.find(task_id)
    @subtasks = @task.subtasks.where(father_subtask_id: nil)
  end

  private

  def update_task_params
    params.permit(:done)
  end

  def task_id
    params[:id]
  end

  def task_params
    params.permit(:list_id, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_for(task)
    clazz = [ 'task' ]
    if task.done?
      clazz << 'done'
    end

    clazz.join(' ')
  end

  def task_list_for(label, items, context_class, link_path)
    content_tag :article, class: "task-list #{context_class}" do
      content = "<h2>#{link_to label, link_path, class: 'text-info'}</h2>"
      content += "<table class='table table-hover'>
                  <tbody>"

      items.map do |list|
        content += content_tag :tr do
          link = link_to(list.name, list_path(list), class: 'list-link')
          content_tag :td, link, class: "list#{ ' public' if list.public? }".html_safe
        end.html_safe
      end.join.html_safe

      content += "</tbody>
              </table>"

      content.html_safe
    end.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<% if @lists.size > 0 %>
    <div class="container">
      <div class="col-xs-12 col-sm-9">
        <div class="jumbotron">
          <h1>Showable Lists</h1>
          <p>
          <table class='table table-hover'>
            <tbody>
            <% @lists.each do |list| %>
                <tr>
                  <td>
                    <%= link_to list.name, list_path(list), class: 'text-muted list' %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
          </p>
        </div>
      </div>
    </div>
<% else %>
    <p>No lists to show</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Todo Lists</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Todo Lists', root_path, class: 'navbar-brand'%>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path, class: 'active'%></li>
        <li><%= link_to 'Create List', '/lists/new', class: 'active'%></li>
        <% if user_signed_in? %>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'sign-out general-link' %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/lists/new.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-9">
    <div class="jumbotron">
      <h1>New List</h1>
      <p>
      <div class="form">
        <%= form_for @list, html: {class: 'simple_form new_list' } do |f| %>
            <%= f.text_field :name, placeholder: 'List name', class: ' input-small form-name' %>
            <br/>
            <%= f.check_box :public, checked_value: true, unchecked_value: false, class: 'checkbox-form' %>
            <%= f.label :public, 'Make it public!' %>
            <br/>
            <%= f.submit 'Create my list', class: 'btn form-button' %>
        <% end %>
      </div>
      </p>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-9">
    <div class="jumbotron">
      <h1><%= @list.name %></h1>
      <p>
        <%= check_box_tag('Favorite', @list.id, current_user.favorited?(@list), { 'id' => 'favorite', 'class' => 'favorite' }) %> Favorite
      </p>
      <p>
        <%= check_box_tag('Make it public!', @list.id, @list.public, { 'id' => 'public_list', 'class' => 'public_list' }) %> Make it public!
      </p>
      <h3> Task's </h3>
      <p>
      <div class="form">
        <%= form_for @list, html: {class: 'simple_form edit_list' } do |f| %>
            <% f.fields_for :tasks do |post_form| %>
                <%= post_form.text_field :name, placeholder: 'New Task name', class: 'input-small form-name new_task', disabled: !@list.created_by?(current_user) %>
            <% end %>
        <% end %>
      </div>
      </p>
      <p>
      <div class="tasks" data-url="<%= list_tasks_path(@list) %>">
        <ul class="list-unstyled">
          <% @list.tasks.each do |task| %>
              <li class="<%= class_for(task) %>"
                  data-url="<%= list_task_path(@list.id, task) %>">
                <%= check_box_tag(task.name, task.id, task.done?,
                                  disabled: !@list.created_by?(current_user)) %>
                <%= link_to task.name, list_task_path(task.list.id, task.id), class: 'list-link list favorite' %>
              </li>
          <% end %>
        </ul>
      </div>
      </p>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-9">
    <div class="jumbotron">
      <h1><%= @task.list.name %></h1>
      <h3> Task's </h3>
      <p>
      <div class="form">
        <%= form_for @task, html: {class: 'simple_form' } %>
        <br/>
      </div>
      </p>
    </div>
  </div>
</div>